biobank_reports.Rmd:
  path: dev/biobank_reports.Rmd
  state: active
  R:
  - R/any_pos_any_neg.R
  - R/data_table.R
  - R/get_aliquot_number.R
  - R/get_event_id.R
  - R/get_find_study_id.R
  - R/get_patient_id.R
  - R/get_site_id.R
  - R/get_specimen_type_id.R
  - R/rm_form_name.R
  - R/num_thousandth_sep.R
  - R/read_multiple_files.R
  - R/read_multiple_sheets.R
  - R/rm_all_na_col.R
  - R/summarise_categorical_vars.R
  tests:
  - tests/testthat/test-data_table.R
  - tests/testthat/test-read_multiple_sheets.R
  - tests/testthat/test-any_pos_any_neg.R
  - tests/testthat/test-rm_all_na_col.R
  - tests/testthat/test-read_multiple_files.R
  - tests/testthat/test-summarise_categorical_vars.R
  - tests/testthat/test-get_find_study_id.R
  - tests/testthat/test-get_site_id.R
  - tests/testthat/test-get_event_id.R
  - tests/testthat/test-get_specimen_type_id.R
  - tests/testthat/test-get_aliquot_number.R
  - tests/testthat/test-get_patient_id.R
  - tests/testthat/test-num_thousandth_sep.R
  - tests/testthat/test-rm_form_name.R
  vignettes: vignettes/biobank-reports.Rmd
  inflate:
    flat_file: dev/biobank_reports.Rmd
    vignette_name: biobank-reports
    open_vignette: true
    check: true
    document: true
    overwrite: ask
OpenSpecimenAPI.Rmd:
  path: dev/OpenSpecimenAPI.Rmd
  state: active
  R:
  - R/auth_os.R
  - R/get_all_sites.R
  - R/get_bulk_order_detail.R
  - R/get_bulk_order_items.R
  - R/get_bulk_orders.R
  - R/get_bulk_query.R
  - R/get_bulk_site_details.R
  - R/get_order_detail.R
  - R/get_order_items.R
  - R/get_orders.R
  - R/get_os_query.R
  - R/get_os_site.R
  - R/parse_all_sites.R
  - R/parse_data.R
  - R/parse_order_detail_data.R
  - R/parse_os_oder_list.R
  - R/parse_os_order_data.R
  - R/parse_os_response.R
  - R/parse_site_details.R
  - R/timestamp_to_date.R
  tests:
  - tests/testthat/test-auth_os.R
  - tests/testthat/test-timestamp_to_date.R
  - tests/testthat/test-parse_os_response.R
  - tests/testthat/test-parse_data.R
  - tests/testthat/test-get_os_query.R
  - tests/testthat/test-get_bulk_query.R
  - tests/testthat/test-parse_os_order_data.R
  - tests/testthat/test-get_bulk_orders.R
  - tests/testthat/test-parse_order_detail_data.R
  - tests/testthat/test-get_order_detail.R
  - tests/testthat/test-get_bulk_order_detail.R
  - tests/testthat/test-parse_os_oder_list.R
  - tests/testthat/test-get_order_items.R
  - tests/testthat/test-parse_all_sites.R
  - tests/testthat/test-get_bulk_order_items.R
  - tests/testthat/test-get_all_sites.R
  - tests/testthat/test-parse_site_details.R
  - tests/testthat/test-get_os_site.R
  - tests/testthat/test-get_bulk_site_details.R
  vignettes: vignettes/open-specimen-api.Rmd
  inflate:
    flat_file: dev/OpenSpecimenAPI.Rmd
    vignette_name: Open-Specimen-API
    open_vignette: true
    check: true
    document: true
    overwrite: ask
sample_selections.Rmd:
  path: dev/sample_selections.Rmd
  state: active
  R:
  - R/append_check_col.R
  - R/convert_os_df_to_wide.R
  - R/create_save_workbook.R
  - R/gen_clinical_data.R
  - R/make_clean_os_names.R
  - R/process_save_selected_aliquots.R
  - R/read_os_data.R
  - R/samples_distributed_summary.R
  - R/select_many_aliquots.R
  - R/select_one_aliquot.R
  - R/selected_aliquots_df.R
  tests:
  - tests/testthat/test-convert_os_df_to_wide.R
  - tests/testthat/test-select_one_aliquot.R
  - tests/testthat/test-select_many_aliquots.R
  - tests/testthat/test-selected_aliquots_df.R
  - tests/testthat/test-make_clean_os_names.R
  - tests/testthat/test-read_os_data.R
  - tests/testthat/test-append_check_col.R
  - tests/testthat/test-process_save_selected_aliquots.R
  - tests/testthat/test-create_save_workbook.R
  - tests/testthat/test-gen_clinical_data.R
  - tests/testthat/test-samples_distributed_summary.R
  vignettes: vignettes/sample-selections-vignette.Rmd
  inflate:
    flat_file: dev/sample_selections.Rmd
    vignette_name: sample-selections-vignette
    open_vignette: true
    check: true
    document: true
    overwrite: ask
