biobank_reports.Rmd:
  path: dev/biobank_reports.Rmd
  state: active
  R:
  - R/any_pos_any_neg.R
  - R/data_table.R
  - R/get_aliquot_number.R
  - R/get_event_id.R
  - R/get_find_study_id.R
  - R/get_site_id.R
  - R/get_specimen_type_id.R
  - R/read_multiple_files.R
  - R/read_multiple_sheets.R
  - R/rm_all_na_col.R
  - R/summarise_categorical_vars.R
  tests:
  - tests/testthat/test-data_table.R
  - tests/testthat/test-read_multiple_sheets.R
  - tests/testthat/test-any_pos_any_neg.R
  - tests/testthat/test-rm_all_na_col.R
  - tests/testthat/test-read_multiple_files.R
  - tests/testthat/test-summarise_categorical_vars.R
  - tests/testthat/test-get_find_study_id.R
  - tests/testthat/test-get_site_id.R
  - tests/testthat/test-get_event_id.R
  - tests/testthat/test-get_specimen_type_id.R
  - tests/testthat/test-get_aliquot_number.R
  vignettes: vignettes/biobank-reports.Rmd
  inflate:
    flat_file: dev/biobank_reports.Rmd
    vignette_name: biobank-reports
    open_vignette: true
    check: true
    document: true
    overwrite: ask
sample_selections.Rmd:
  path: dev/sample_selections.Rmd
  state: active
  R:
  - R/append_check_col.R
  - R/convert_os_df_to_wide.R
  - R/create_save_workbook.R
  - R/gen_clinical_data.R
  - R/make_clean_os_names.R
  - R/process_save_selected_aliquots.R
  - R/read_os_data.R
  - R/samples_distributed_summary.R
  - R/select_many_aliquots.R
  - R/select_one_aliquot.R
  - R/selected_aliquots_df.R
  tests:
  - tests/testthat/test-convert_os_df_to_wide.R
  - tests/testthat/test-select_one_aliquot.R
  - tests/testthat/test-select_many_aliquots.R
  - tests/testthat/test-selected_aliquots_df.R
  - tests/testthat/test-make_clean_os_names.R
  - tests/testthat/test-read_os_data.R
  - tests/testthat/test-append_check_col.R
  - tests/testthat/test-process_save_selected_aliquots.R
  - tests/testthat/test-create_save_workbook.R
  - tests/testthat/test-gen_clinical_data.R
  - tests/testthat/test-samples_distributed_summary.R
  vignettes: vignettes/sample-selections-vignette.Rmd
  inflate:
    flat_file: dev/sample_selections.Rmd
    vignette_name: sample-selections-vignette
    open_vignette: true
    check: true
    document: true
    overwrite: ask
