# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

# Test the function with custom subfolders and a custom suffix
test_that("create_folders with custom subfolders and suffix", {
  # Test setup: create a temporary path for testing
  path_name <- tempfile(pattern = "main_folder") %>%
    normalizePath(winslash = "/")

  create_folders(path_name, c("archive", "temp", "shared"), "_dir")
  expect_true(dir.exists(file.path(path_name, "archive")))
  expect_true(dir.exists(file.path(path_name, "temp")))
  expect_true(dir.exists(file.path(path_name, "shared")))
  # Check if global variables are correctly assigned
  expect_identical(get("archive_dir", envir = .GlobalEnv), file.path(path_name, "archive"))
  expect_identical(get("temp_dir", envir = .GlobalEnv), file.path(path_name, "temp"))
  expect_identical(get("shared_dir", envir = .GlobalEnv), file.path(path_name, "shared"))
})

