# WARNING - Generated by {fusen} from /dev/biobank_reports.Rmd: do not edit by hand

test_that("data_table displays datatable correctly", {
  df <- iris[1:10,]
  output <- data_table(df, pageLength = 10, file_name = "")
  
  # Test if the output contains expected elements
  expect_true(inherits(output, "datatables"))
  
  expect_error(data_table(df = c(1,2,3)),
               regexp ="df must be a data.frame")

})

