# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("mark_all_duplicates works", {
  expect_true(inherits(mark_all_duplicates, "function")) 
})
