# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("create_save_workbook works", {
  expect_true(inherits(create_save_workbook, "function")) 
})
