# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("append_check_col works", {
  expect_true(inherits(append_check_col, "function")) 
})
