# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

test_that("rm_form_name works", {
  expect_true(inherits(rm_form_name, "function")) 
})

test_that("groupby_vec works", {
  expect_true(inherits(groupby_vec, "function")) 
})
