# WARNING - Generated by {fusen} from /dev/sample_selections.Rmd: do not edit by hand

test_that("select_one_aliquot works", {
  
  samples_list <- list(c("TB0990100010101001", 
                         "TB0990100010101002",
                         "TB0990100010101003"))
  
  expect_warning(select_one_aliquot(samples_list, aliquot_number = 4),
                 regxp ="Subscript out of bounds returning NA" )
  expect_equal(select_one_aliquot(samples_list, aliquot_number = 1),"TB0990100010101001" )
})
