# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

test_that("process_save_selected_aliquots works", {
  expect_true(inherits(process_save_selected_aliquots, "function")) 
})
