# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("gen_clinical_data works", {
  expect_true(inherits(gen_clinical_data, "function")) 
})
