# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("select_and_shuffle_dt works", {
  expect_true(inherits(select_and_shuffle_dt, "function")) 
})
