# WARNING - Generated by {fusen} from /dev/sample_selections.Rmd: do not edit by hand

test_that("convert_os_df_to_wide  works", {
  library(data.table)
  data("tb_data", package = "findBiobankR")
  setnames(tb_data, "ppid", "ppid2")
  data("tb_specimen_df", package = "findBiobankR")
  
  expect_error( convert_os_df_to_wide(clinical_df = tb_data,
                                      specimen_df = tb_specimen_df, 
                                      join_by_col = "ppid",
                                      specimen_col ="specimen_type" ,
                                      clinical_vars = clinical_cols ,
                                      os_aliquot_names = c("Serum", "Plasma")),
                regxp ="The column 'join_by_col' does not exist in the data frames." )
})
