# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("selected_aliquots_df works", {
  expect_true(inherits(selected_aliquots_df, "function")) 
})
