# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("samples_distributed_summary works", {
  expect_true(inherits(samples_distributed_summary, "function")) 
})
