# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand


test_that("select_patients_per_group works", {
  expect_true(inherits(select_patients_per_group, "function")) 
})


