# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

test_that("summarise_categorical_vars works", {
  expect_true(inherits(summarise_categorical_vars, "function")) 
})
