# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

test_that("get_bulk_orders works", {
  expect_true(inherits(get_bulk_orders, "function")) 
})

test_that("get_orders works", {
  expect_true(inherits(get_orders, "function")) 
})
