# WARNING - Generated by {fusen} from /dev/biobank_reports.Rmd: do not edit by hand

# Test that the function correctly identifies columns with more than 99% missing values.
test_that("The function correctly identifies columns with more than 99% missing values", {
  
  library(data.table)
  df <- data.table(
  id = 1:10,
  name = c("John", "Jane", "", "Mary", "Mike", "", "", "Peter", "Sam", "Susan"),
  age = c(20, 21, 18, 22, 23, 19, NA, 24, 25, 26),
  height = c(170, 160, 180, 175, 185, 175, NA, 190, 195, 200),
  plasma_collected = rep(NA, 10)
)
 rm_all_na_col(df, missing_per = 99.99)
 expect_equal(names(df), c("id", "name", "age", "height"))
  
  # Test that the function correctly drops columns with more than 99% missing values.
  expect_false("plasma_collected" %in% names(df))
})

