# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("read_os_data works", {
  expect_true(inherits(read_os_data, "function")) 
})
