# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Find any positve gven a list of column
#' 
#' Given a list of column names eg symptoms find if there are any positives
#' @param df A data.frame or data.table or tibble 
#' @param test_cols a vector of column names eg cols measuring symptoms
#' @param neg_value a value that shows  the negative outcome in test_cols
#' @param pos_value a value that measures the positive outcome in test_cols
#' @param id_cols A vector of column names in df that you would want included eg participant ID
#' @param test_type vector of length one to be appended to output name
#' @importFrom data.table setDT 
#' @return A data.table
#' 
#' @export
#' @examples
#' data("tb_resp_symptoms")
#'
#' respirotory_symptoms <- c("COUGH", "EXPECTORATION",
#'                           "HEMOPTYSIS", "CHEST_PAIN",
#'                           "DYSPNOE")
#'
#' any_pos_any_neg(df = tb_resp_symptoms, 
#'                  test_cols =respirotory_symptoms ,
#'                  test_type = "resp_symp" ,
#'                  neg_value ="No",
#'                  pos_value = "Yes",
#'                  id_cols ="ID")
any_pos_any_neg <-  function(df, 
                             test_cols,
                             test_type ,
                             neg_value ="No",
                             pos_value = "Yes",
                             id_cols =c("Participant_PPID") ){
  
  
  if(isFALSE(inherits(df, "data.table"))){
    
      setDT(df)
  }
  
   if(isFALSE(length(test_type) == 1)){
    
      stop("test_type should be a vector of length one")
  }


  df[, (test_cols) := lapply(.SD, function(x) ifelse(is.na(x), "", x)), .SDcols = test_cols]

  any_neg = paste0(test_type, "_any_neg")
  any_pos = paste0(test_type, "_any_pos")
  pos_no = paste0(test_type, "_pos_no")
  neg_no = paste0(test_type, "_neg_no")
  
  row_nums = seq_len(nrow(df))
  
  cols_interest <- c(id_cols,any_neg,
                     any_pos,  pos_no,
                     neg_no)
  
  df[, (any_pos) := any(.SD== pos_value), .SDcols = test_cols , by = row_nums]
  
  df[, (any_neg) := any(.SD== neg_value), .SDcols = test_cols , by = row_nums]
  
  
  df[, (pos_no) :=sum(.SD ==pos_value), .SDcols = test_cols, by = row_nums]
  
  
  df[, (neg_no) :=sum(.SD == neg_value), .SDcols = test_cols, by = row_nums]
  
  df <- df[, .SD, .SDcols = cols_interest]
  
  df
}
