# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Append excel if condition
#' @description
#' usually we usually add a true false column to check if the shipped barcode is 
#' the barcode/specimen label  we selected. This function does exactly that it combines
#' OS data set and selected 
#' @param selected_samples A data frame from findBiobankR::selected_aliquots_df. If this is null please ensure that
#' os data set contains only column to send 
#' @param os_position This a data set that comes from open specimen
#' @param ppid_col Participant id column. 
#' @param specimen_id_col Specimen ID column name
#' @param os_required_cols Column names required to send a list to a requester
#' @param scanned_bar_code_col The name of the barcode column name with retrieved specimens 
#' @importFrom utils object.size
#' @importFrom data.table fifelse setDT
#' @return A data.table with a checked column 
#' 
#' @export
#' @examples
#'
#' library(data.table)
#' library(dplyr)
#' data("tb_data", package = "findBiobankR")
#' #data("tb_specimen_df", package = "findBiobankR")
#'
#' # required clinical cols
#' clinical_cols <- c("tb_group", "hiv_status", "sex", "country") 
#'
#' clin_specs  <- convert_os_df_to_wide(clinical_df = tb_data,
#'                                      specimen_df = tb_specimen_df, 
#'                                      join_by_col = "ppid",
#'                                      specimen_col ="specimen_type" ,
#'                                      clinical_vars = clinical_cols ,
#'                                      specimen_label_col = "specimen_label",
#'                                      os_aliquot_names = c("Serum", "Plasma")
#' )
#'
#'
#' clin_specs[, serum_aliquot := select_one_aliquot(NP_labels_serum, aliquot_number = 1 )]
#' clin_specs[, plasma_aliquot := select_one_aliquot(NP_labels_plasma, aliquot_number= 1 )]
#'
#' # or tidyverse way
#'
#' selected_samples <- selected_aliquots_df(clin_specs,
#'                                          aliquot_cols = c("serum_aliquot","plasma_aliquot"),
#'                                          ppid_col = "ppid")
#'
#' df_send <- append_check_col(selected_samples = selected_samples,
#'                             os_position = tb_specimen_df,
#'                             ppid_col = "ppid",
#'                             specimen_id_col = "specimen_label",
#'                             os_required_cols = c("ppid",
#'                                                  "Specimen_Specimen Label",
#'                                                  "Specimen_Type", 
#'                                                  "Specimen_Requirement Name", 
#'                                                  "Specimen_Barcode",
#'                                                  "Specimen_Container Name", 
#'                                                  "Specimen_Container Position",
#'                                                  "Scanned_barcode"))
#'
#' df_send

# nms_new_pos <- c( "Specimen_Type", "Specimen_Requirement Name", 
#                   "Specimen_Specimen Label", "Specimen_Barcode", "Specimen_Container Name", 
#                   "Specimen_Container Position", "Scanned_barcode")
# 
# nms_old_pos <- c( "specimen_type", "specimen_requirement_name", 
#                   "specimen_label", "specimen_barcode", "specimen_container_name", 
#                   "specimen_container_position", "scanned_barcode")

append_check_col <- function(selected_samples,
                             os_position,
                             ppid_col = "Participant_PPID",
                             specimen_id_col = "specimen_label",
                             os_required_cols = c("Participant_PPID",
                                                  "Specimen_Specimen Label",
                                                  "Specimen_Type", 
                                                  "Specimen_Requirement Name", 
                                                  "Specimen_Barcode",
                                                  "Specimen_Container Name", 
                                                  "Specimen_Container Position",
                                                  "Scanned_barcode"),
                             scanned_bar_code_col = "Scanned_barcode"){
  
  
  join_by_col = c(ppid_col, specimen_id_col)
  object_size = object.size(os_position)
  os_position[, (scanned_bar_code_col) := ""]
  
  
  nms_old_pos = make_clean_os_names(os_required_cols)
  
  if(isFALSE(is.null(selected_samples))){
    
    os_selected <- merge(selected_samples,
                         os_position, 
                         by = join_by_col)
    
  }else{
    
    os_selected = os_position
    
  }
  
  make_clean_os_names(os_selected)
  
  nms_os_c = names(os_selected)
  
  if(isFALSE(all(nms_old_pos %in% nms_os_c))){
    
    nms_missing = nms_old_pos[!nms_old_pos %in% nms_os_c] %>%
      paste0(collapse = ",")
    msg = sprintf("The following required column names were not found %s", nms_missing)
    stop(msg)
    
  }
  
  setDT(os_selected)
  
  
  
  os_selected <- os_selected[, ..nms_old_pos]
  os_selected[, specimen_barcode := gsub("^0","", specimen_barcode) ]
  os_selected[, specimen_barcode := paste0("0", specimen_barcode) ]
  nms_f <- names(os_selected)
  
  barcode_id <- which(nms_f == "specimen_barcode")
  scanned_id <- which(nms_f == "scanned_barcode")
  barcode_letter <- LETTERS[barcode_id]
  scanned_barcode_letter <- LETTERS[scanned_id]
  n_rows = 1:nrow(os_selected)
  excel_rows = n_rows+1
  barcode_rows <- paste0(barcode_letter, excel_rows)
  scanned_barcode_rows <- paste0(scanned_barcode_letter, excel_rows)
  os_selected[, checked :=paste0("IF(", barcode_rows,"=",scanned_barcode_rows,",1", ", 0",")" ) ]
  
  
  os_selected[, specimen_barcode := fifelse(specimen_barcode == "0", specimen_label,specimen_barcode ) ]
  
  setnames(os_selected, nms_old_pos, os_required_cols)
  
  class(os_selected$checked) <- c(class(os_selected$checked), "formula")
  
  os_selected
}
