# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Authenticate to the OpenSpecimen API
#'
#' This function authenticates a user to the OpenSpecimen API using the provided
#' URL, username, and password.
#'
#' @param url The URL of the OpenSpecimen API.
#' @param username The username for authentication.
#' @param password The password for authentication.
#' @param domain_name The domain name (default is "openspecimen").
#'
#' @return A list with the URL and the authentication response which contains auth token and user details
#' @importFrom httr POST  add_headers content status_code
#' @note See additional information on this API on https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/1116035/REST+APIs
#' @export
#' 
#' @examples
#'
#' # os_test_url <- Sys.getenv("OSTESTURL")
#' # os_test_username <- Sys.getenv("OSUSERNAME")
#' # os_test_password <- Sys.getenv("OSPASSWORDTEST")
#' # 
#' # auth_repo <- auth_os(url = os_test_url,
#' #                      username = os_test_username,
#' #                      password = os_test_password)
#'
auth_os <- function(url ,
                    username,
                    password, 
                    domain_name = "openspecimen") {
    # Define the login request data as a JSON object
    sessions_url <- paste0(url, "/sessions")
    
    login <- list(
        loginName = username,
        password = password,
        domainName = domain_name
    )
    
    # Specify the content type as JSON in the header
    headers <- add_headers("Content-Type" = "application/json")
    
    # Make the POST request for authentication
    response <- POST(
        url = sessions_url,
        body = login,
        config = headers,
        encode = "json"
    )
    
    # Check the response status code
    status_code <- status_code(response)
    
    if (status_code %in% c(200, 201)) {
        # Authentication successful, return the response content
        auth_res = content(response, "parsed")
        return(list(url = url, auth_response = auth_res))
        
    } else {
        # Authentication failed, return an error message or handle it as needed
        error_message <- content(response, "text")
        
        stop(paste("Authentication failed with status code", status_code, ":", error_message))
    }
}

