# WARNING - Generated by {fusen} from /dev/sample_selections.Rmd: do not edit by hand




#' Convert  OS data to wide
#' 
#' Convert OS data to wide and merge with clinical data
#' 
#' @param clinical_df A data frame with clinical data at Find typically from Open Clinica.
#' @param specimen_df A data frame with specimen data at Find generally Open Specimen.
#' @param os_aliquot_names A vector of the aliquot names that you want to use. 
#' @param join_by_col A column used to merge clinical data and specimen data
#' @param join_function A function in char to join with. Recommended to use
#'  dplyr merge function eg left_join, inner_join etc. Recommended to load dplyr 
#' @param specimen_col The column containing specimen names.
#'  At find usually Specimen Requirement name
#' @param clinical_vars A vector of clinical variables.
#'  Ideally variables that usually describe patient characteristics eg sex, 
#'  disease information etc
#' @param specimen_label_col Column containing specimen IDS in Open Specimen this is 
#'  specimen label
#' @importFrom janitor make_clean_names
#' @importFrom data.table setnames setDT 
#' @importFrom purrr reduce
#' @return A wide data frame with one row per participant and one column for
#'   each aliquot name and the number of aliquots and the specimen labels for
#'   that aliquot.
#'
#' @export

#' @examples
#' library(data.table)
#' library(dplyr)
#' data("tb_data", package = "findBiobankR")
#' data("tb_specimen_df", package = "findBiobankR")
#' 
#' # required clinical cols
#' clinical_cols <- c("tb_group", "hiv_status", "sex", "country") 
#' 
#' clin_specs  <- convert_os_df_to_wide(clinical_df = tb_data,
#'                                      specimen_df = tb_specimen_df, 
#'                                      join_by_col = "ppid",
#'                                      specimen_col ="specimen_type" ,
#'                                      clinical_vars = clinical_cols ,
#'                                      specimen_label_col = "specimen_label",
#'                                      os_aliquot_names = c("Serum", "Plasma")
#' )
#' 
#' knitr::kable(clin_specs[1:10, ])
convert_os_df_to_wide <- function(clinical_df,
                                  specimen_df, 
                                  join_by_col,
                                  specimen_col,
                                  specimen_label_col,
                                  clinical_vars = NULL ,
                                  os_aliquot_names,
                                  join_function = "left_join") {
  
  # Check if input data frames are provided
  if (is.null(clinical_df) || is.null(specimen_df)) {
    stop("Input data frames 'clinical_df' and 'specimen_df' are required.")
  }
  
  # Check if join_by_col and specimen_col are present in the data frames
  if (!(join_by_col %in% names(clinical_df)) || !(join_by_col %in% names(specimen_df))) {
    stop("The column 'join_by_col' does not exist in the data frames.")
  }
  
  if (!(specimen_col %in% names(specimen_df))) {
    stop("The column 'specimen_col' does not exist in the 'specimen_df' data frame.")
  }
  
  # Check if os_aliquot_names is provided
  if (length(os_aliquot_names) == 0) {
    stop("The 'os_aliquot_names' vector is empty.")
  }
  
  # Clean the aliquot names.
  os_aliquot_names_clean <- make_clean_names(os_aliquot_names)
  
  # Create a list of data frames, one for each aliquot name.
  list_dfs = vector(mode = "list",
                    length = length(os_aliquot_names))
  
  for (i in seq_along(os_aliquot_names)) {
    
    aliq_name = os_aliquot_names[i]
    
    aliq_col_name = os_aliquot_names_clean[i]
    
    no_aliquots = paste0("NP_aliqN_",
                         aliq_col_name)
    aliquots_spec_label = paste0("NP_labels_", 
                                 aliq_col_name)
    
    new_nms = c(no_aliquots, aliquots_spec_label)
    
    old_nms = c("NP_aliqN", "NP_labels")
    # calculate aliquot numbers and 
    
    aliquot_samples_df <- specimen_df[get(specimen_col) == aliq_name,
                                      list(NP_aliqN = .N,
                                        NP_labels = list(get(specimen_label_col))),
                                      by = join_by_col]
    
    
    setnames(aliquot_samples_df,
             old_nms, 
             new_nms)
    
    list_dfs[[i]] = aliquot_samples_df
    
  }
  ## function use to merge data frames
  join_function <- match.fun(join_function)
  # Combine the list of data frames into a single data frame.
  final_df <- list_dfs %>% 
    reduce(join_function,
           by = join_by_col)
  
  # Set the data frame as a data table.
  
  setDT(final_df)
  
  # select only the variables required from clinical data
  if(!is.null(clinical_vars)){
    
    clinical_vars = c(join_by_col, clinical_vars)
    
    clinical_df = clinical_df[, .SD, 
                              .SDcols = clinical_vars]
  }
   ## merge with clinical df
  final_df <- merge(clinical_df,
                    final_df,
                    by = join_by_col,
                    all.x = T)
  
  
  # Return the wide data frame.
  final_df
}
