# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Create Project Folders
#'
#' This function creates a set of folders for a project, including a main folder and specified subfolders.
#' It optionally assigns global variable names for each folder path, using a provided suffix.
#'
#' @param main_folder A string specifying the path of the main project folder.
#' @param subfolders A character vector of subfolders to be created within the main folder.
#'                   Default is c("data", "results", "doc").
#' @param suffix A string to append to each subfolder name when creating global variables.
#'               Default is "_folder".
#' @importFrom stats  setNames
#' @export
#' @examples
#' path_name <- tempfile(pattern = "main_folder") %>%
#'     normalizePath(winslash = "/")
#'
#' create_folders(path_name)
#'
#' # Specify different subfolders and a custom suffix
#' create_folders(path_name, c("archive", "temp", "shared"), "_dir")
#'
create_folders <- function(main_folder, subfolders = c("data", "results", "doc"), suffix = "_folder") {
  # Create a list of folder paths by appending each subfolder name to the main folder path
  folders_to_create <- setNames(
    lapply(subfolders, function(subfolder) paste0(main_folder, "/", subfolder)),
    paste0(subfolders, suffix)
  )
  
  # Add the main folder path to the list, without the suffix
  folders_to_create$main_folder <- main_folder
  
  # Create each folder if it does not exist
  for (folder_name in names(folders_to_create)) {
    folder_path <- folders_to_create[[folder_name]]
    if (!dir.exists(folder_path)) {
      dir.create(folder_path, recursive = TRUE)
      cat(sprintf("Created folder: %s\n", folder_path))
    } else {
      cat(sprintf("Folder already exists: %s\n", folder_path))
    }
    # Optionally, assign folder path to global environment
    assign(folder_name, folder_path, envir = .GlobalEnv)
  }
}

