# WARNING - Generated by {fusen} from /dev/biobank_reports.Rmd: do not edit by hand

#' data_table function
#'
#' This function creates a datatable from a data frame using the DT package.
#'
#' @param df The data frame to be displayed as a datatable.
#' @param pageLength The number of rows to display per page. Default is 50.
#' @param row_names Logical value indicating whether to display row names. Default is FALSE.
#' @param file_name The name of the file to be used for exporting data. 
#' @importFrom DT datatable
#' @return An interactive data table of class DT
#' @export
#' @examples
#'  data("iris")
#' df = iris[1:10,]
#' 
#' data_table(df, 
#'            file_name = "iris_sub_df")
data_table <- function(df, pageLength = 50, 
                       row_names = FALSE,
                       file_name = "output_file") {
    
    stopifnot("Data frame must be provide"=!missing(df))
    
    if(isFALSE(inherits(df, "data.frame"))){
        stop("df must be a data.frame")
    }
    

    n_col <- ncol(df) - 1
    datatable(df,
              rownames = row_names,
              extensions = 'Buttons',
              #style = "bootstrap4",
              #class = 'cell-border stripe',
              options = list(
                  scrollX = TRUE,
                  pageLength = pageLength,
                  dom = 'Blfrtip',
                  buttons = list(
                      list(extend = 'copy', filename = file_name),
                      list(extend = 'csv', filename = file_name),
                      list(extend = 'excel', filename = file_name),
                      list(extend = 'pdf', filename = file_name)
                  ),
                  columnDefs = list(
                      list(className = 'dt-center', targets = 0:n_col)
                  )
              )
    )
}

