# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Provide a list of dfs with clinical samples and dictionary data set
#' 
#' This function processes clinical data set, lab data set and a dictionary. 
#' 
#' @param clinical_data Clinical data set
#' @param clinical_cols  Clinical column names to cinclude 
#' @param selected_samples_df aliquots to send ideally a data.frame from  findBiobankR::process_save_selected_aliquots or lab data specimen data
#' @param specimen_cols Required columns from specimen data frame 
#' @param dictionary Dictionary to provide to sample requester 
#' @param ppid_col Participant id column A column that should be in `selected_samples_df` and `clinical_data` for merging 
#' @param dict_variable dictionary variable name containing clinical cols 
#' @param additional_data and Additiona data frame that should contain `ppid_col`
#' @return A list of data.frames 
#' @export
#' @examples
#' library(data.table)
#' library(dplyr)
#' data("tb_data", package = "findBiobankR")
#' data("tb_specimen_df", package = "findBiobankR")
#' data("tb_dictionary", package = "findBiobankR")
#' # required clinical cols
#' clinical_cols <- c("tb_group", "hiv_status", "sex", "country") 
#'
#' clin_specs  <- convert_os_df_to_wide(clinical_df = tb_data,
#'                                      specimen_df = tb_specimen_df, 
#'                                      join_by_col = "ppid",
#'                                      specimen_col ="specimen_type" ,
#'                                      clinical_vars = clinical_cols ,
#'                                      specimen_label_col = "specimen_label",
#'                                      os_aliquot_names = c("Serum", "Plasma")
#' )
#'
#'
#' clin_specs[1:4, serum_aliquot := select_one_aliquot(NP_labels_serum, aliquot_number = 1 )]
#' clin_specs[1:4, plasma_aliquot := select_one_aliquot(NP_labels_plasma, aliquot_number= 1 )]
#'
#'
#' selected_samples <- selected_aliquots_df(clin_specs,
#'                                          aliquot_cols = c("serum_aliquot","plasma_aliquot"),
#'                                          ppid_col = "ppid")
#'
#' selected_samples_df <- process_save_selected_aliquots(file_path = NULL,
#'                                save_file= FALSE,
#'                                selected_samples = selected_samples,
#'                                os_position = tb_specimen_df,
#'                                ppid_col = "ppid",
#'                                specimen_id_col = "specimen_label",
#'                                os_required_cols = c("ppid",
#'                                                     "Specimen_Specimen Label",
#'                                                     "Specimen_Type",
#'                                                     "Specimen_Requirement Name", 
#'                                                     "Specimen_Barcode",
#'                                                     "Specimen_Container Name", 
#'                                                     "Specimen_Container Position",
#'                                                     "Scanned_barcode"))
#'
#' gen_clinical_data(clinical_data = tb_data,
#'                   clinical_cols= clinical_cols,
#'                   dictionary = tb_dictionary,
#'                   selected_samples_df = selected_samples_df,
#'                   ppid_col = "ppid",
#'                   dict_variable = "variable_name",
#'                   specimen_cols = c("ppid", "Specimen_Specimen Label", "Specimen_Type"),
#'                   additional_data = NULL )
#'
gen_clinical_data <- function(clinical_data,
                              clinical_cols,
                              dictionary,
                              selected_samples_df,
                              ppid_col,
                              dict_variable,
                              specimen_cols = c("Participant_PPID", "Specimen_Barcode", "Specimen_Specimen Label"),
                              additional_data = NULL ){
  
  setDT(clinical_data)
  setDT(selected_samples_df)
  setDT(selected_samples_df)
  setDT(dictionary)
  nms_clinical = names(clinical_data)
  nms_selected_samples = names(selected_samples_df)
  
  if(isFALSE(all(specimen_cols %in% nms_selected_samples))){
    
    nms_missing = specimen_cols[!specimen_cols %in% nms_selected_samples] %>%
      paste0(collapse = ",")
    msg = sprintf("The following required column names were not found  %s in selected_samples_df", nms_missing)
    stop(msg)
    
  }
  
  if(isFALSE(all(nms_clinical %in% nms_clinical))){
    
    nms_missing = nms_clinical[!nms_clinical %in% nms_clinical] %>%
      paste0(collapse = ",")
    msg = sprintf("The following required column name %s were not found in clinical_data", nms_missing)
    stop(msg)
    
  }
  
  if (!(ppid_col %in%nms_clinical ) || !(ppid_col %in% nms_selected_samples)) {
    stop("ppid_col is not present in both clinical_data and selected_samples_df")
    
    
    
  }
  clinical_data <- merge(selected_samples_df,
                         clinical_data, by = ppid_col ) 
  
  if(isFALSE(is.null(additional_data))){
    
    nms_additional = names(additional_data)
    
    if (!(ppid_col %in%nms_additional)) {
      
      stop("ppid_col is not present in the additional data set")
    }
    clinical_data <- merge(additional_data,
                           clinical_data, by = ppid_col ) 
    
    
  }else{
    
    nms_additional = NULL
  }
  
  all_cols = c(nms_additional,
               ppid_col, 
               specimen_cols,
               clinical_cols) %>% unique()
  
  clinical_data = clinical_data[, ..all_cols]
  date_cols = clinical_data[, .SD, .SDcols = lubridate::is.Date] %>% names()
  time_cols = clinical_data[, .SD, .SDcols = lubridate::is.timepoint] %>% names()
  date_time_cols = c(date_cols, time_cols) %>% unique()
  
  if(isFALSE(length(date_time_cols) == 0)){
    
    clinical_data[, (date_time_cols) := lapply(.SD, as.character), .SDcols = date_time_cols]
  }
  
  
  clinical_data[, (all_cols) := lapply(.SD, 
                                       function(x) ifelse(x %in% c("Missing", "", "NA"),
                                                          NA, x)), 
                .SDcols = all_cols]
  
  #clinical_data[clinical_data == "Missing"] = NA
  clinical_data <- rm_all_na_col(clinical_data)
  nms_clinical_data <- names(clinical_data)
  dictionary <- dictionary[get(dict_variable) %in%nms_clinical_data ]
  
  list(clinical_data = clinical_data, 
       dictionary = dictionary,
       samples_list = selected_samples_df )
}



