# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get OpenSpecimen Site
#'
#' Use this function to retrieve details of a site from the OpenSpecimen application.
#'
#' @param auth_response Authentication response object obtained from the OpenSpecimen API.
#' @param site_id The unique identifier of the site to fetch.
#'
#' @return A data frame containing the details of the specified site.
#'
#' @export
#' @examples
#' #get_os_site()
get_os_site <- function(auth_response, site_id) {
  
  # Get the site details
  # Specify the content type as JSON in the header
  # Extract the authentication token from the response
  auth_token <- auth_response$auth_response$token
  url <- auth_response$url
  
  headers <- add_headers(
    "Content-Type" = "application/json",
    "X-OS-API-TOKEN" = auth_token
  )
  
  # Make the GET request for the query
  response <- GET(
    url = paste0(url, "/sites/", site_id),
    config = headers,
    encode = "json"
  )
  
  # Parse the response and return the results
  results <- parse_os_response(response, 
                               parse_data_function = "parse_site_details")
  
  # If inherits data.frame, return results, else return NULL
  if (inherits(results, "data.frame")) {
    return(results)
  } else {
    return(NULL)
  }
  
}

