# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Get the site ID from a participant ID in a clinical study.
#'
#' This function extracts the site ID from a participant ID in a FindDX clinical study.
#'
#' @param x A character vector containing participant IDs.
#' @return A character vector containing the site IDs.
#' 
#' @export
#' @examples
#' get_site_id("PP007019990")
get_site_id <- function(x) {
  
  if (!is.character(x)) {
    stop("Input must be a character vector.")
  }
  
  site_id <- stringr::str_sub(x, 6, 7)
  
  return(site_id)
}

