# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Execute a Saved Query
#'
#' This function executes a saved query in the OpenSpecimen API using the provided
#' authentication response and query ID. You can specify the parameters for the query
#' such as driving form, wide row mode, start position, and maximum results.
#'
#' @param auth_response The authentication response obtained from `auth_os`.
#' @param query_id The ID of the saved query to execute.
#' @param driving_form The driving form for the query (default is "Specimen").
#' @param wide_row_mode The wide row mode for the query (default is "OFF").
#' @param start_at The starting position for the query (optional).
#' @param max_results The maximum number of results to retrieve (optional).
#'
#' @return A data frame containing the results of the saved query.
#'

#' @import httr
#' @importFrom httr POST add_headers status_code content
#' @note See additional information on this API on https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/104529939/Query
#' 
#' @export
#' @examples
#'
#' # os_test_url <- Sys.getenv("OSTESTURL")
#' # os_test_username <- Sys.getenv("OSUSERNAME")
#' # os_test_password <- Sys.getenv("OSPASSWORDTEST")
#' # 
#' # auth_repo <- auth_os(url = os_test_url,
#' #                      username = os_test_username,
#' #                      password = os_test_password)
#' # 
#' # get_os_query(auth_repo, query_id = 114,
#' #              driving_form = "Specimen",
#' #              wide_row_mode = "OFF",
#' #              start_at = 0,
#' #              max_results = 5)
get_os_query <- function(auth_response,
                         query_id,
                         driving_form = c("Specimen", "Participant"),
                         wide_row_mode = c("OFF", "DEEP", "SHALLOW"),
                         start_at = NULL,
                         max_results = NULL) {
  # Match the driving_form argument to one of the allowed values
  driving_form <- match.arg(driving_form)
  # Match the wide_row_mode argument to one of the allowed values
  wide_row_mode <- match.arg(wide_row_mode)
  # Extract the authentication token from the response
  auth_token <- auth_response$auth_response$token
  url <- auth_response$url
  # Define the query request data
  query_request <- list(
    drivingForm = driving_form,
    wideRowMode = wide_row_mode,
    startAt = start_at,
    maxResults = max_results
  )
  
  # Specify the content type as JSON in the header
  headers <- add_headers(
    "Content-Type" = "application/json",
    "X-OS-API-TOKEN" = auth_token
  )
  
  # Make the POST request for the query
  response <- POST(
    url = paste0(url, "/query/", query_id),
    body = query_request,
    config = headers,
    encode = "json"
  )
  
  # Check the response status code
  status_code <- status_code(response)
  
  if (status_code == 200) {
    # Query successful, return the parsed response content
    return(parse_data(response))
    
  } else {
    # Query failed, return an error message or handle it as needed
    error_message <- content(response, "text")
    cli::cli_alert_danger(paste("Query failed with status code", status_code, ":", error_message))
  }
}

