# WARNING - Generated by {fusen} from /dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get OpenSpecimen Orders in Bulk
#'
#' This function retrieves a list of orders from the OpenSpecimen API in bulk, handling pagination and combining results. It uses the provided authentication response and optional query parameters for customization.
#'
#' @param auth_response The authentication response obtained from `authenticateOS`.
#' @param include_stats Logical, whether to include statistics (default is TRUE).
#' @param page_size Integer, the number of results to retrieve per page (default is 250).
#' @param max_pages Integer, the maximum number of pages to retrieve (default is 10,000).
#'
#' @return A data frame containing the aggregated order data from multiple pages.
#'

#' @importFrom httr GET add_headers status_code
#'
#' @note This function allows you to efficiently retrieve orders from OpenSpecimen in bulk while handling pagination and result aggregation.
#'
#' @export
#' @examples
#' #get_bulk_orders()
get_bulk_orders <- function(auth_response, 
                            include_stats = TRUE, 
                            page_size = 250,
                            max_pages = 10000) {
  
  # List to store query results
  results_list <-  vector(mode = "list", length = max_pages)
  row_numbers <- vector(mode = "numeric", length = max_pages) 
  
  for (i in  seq_len(max_pages)) {
    j = i - 1
    start_at <- j * page_size
    max_results <- page_size
    
    results <- get_orders(auth_response, include_stats, start_at, max_results)
    
    rows_count <- nrow(results)
    
    if (rows_count > 0) {
      
      results_list[[i]] <- results  # Store the results in the list
      row_numbers[i] <- rows_count  # Store the number of rows retrieved
      cli::cli_alert_success(paste0(num_thousandth_sep(sum(row_numbers)),
                                    " rows retrieved"))
      
    } else {
      
      break  # No more data, exit the loop
    }
  }
  
  # Remove 0-column data frames
  results_list <- results_list[sapply(results_list, function(x) !is.null(x))]
  
  # Return the results as a single data frame
  df_results = data.table::rbindlist(results_list, fill = TRUE) 
  
  return(df_results)
}


#' Parse OpenSpecimen Order Detail Data
#'
#' This function parses the response content from the OpenSpecimen API for order details and organizes it into a data.table.
#'
#' @param response The response object from the Open Specimen API.
#' @param remove_personal_info Logical, whether to remove personal information columns (default is TRUE).
#'
#' @return A data.table containing the parsed order detail data.
#'
#' @importFrom data.table as.data.table data.table
#' @import janitor
#'
#' @export
#' @examples
#' 
#' # order_detail <- parse_order_detail_data(response)
#' 
parse_order_detail_data <- function(response, remove_personal_info = TRUE) {
  
  # Parse the response content
  parsed_cont <- content(response, "parsed") 
  
  # Unlist the parsed content
  parsed_1 <- unlist(parsed_cont, recursive = FALSE) 
  
  # Extract extension details
  extension_details <- parsed_1$distributionProtocol.extensionDetail 
  
  # Extract attribute details
  attr_dp <- extension_details$attrs
  
  # Create clean column names
  col_nms <- sapply(attr_dp, function(x) x$caption) %>% 
    janitor::make_clean_names()
  
  # Extract attribute values
  values <- lapply(attr_dp, function(x) x$value)
  
  # Set names for values
  names(values) <- col_nms
  
  # Convert values to data.table
  dt1 = as.data.table(values)
  
  # Remove extension details from parsed content
  parsed_1$distributionProtocol.extensionDetail <- NULL
  
  # Extract distributing sites
  dist_sites <- parsed_1$distributionProtocol.distributingSites %>%
    unlist() %>%
    paste0(collapse = ",")
  
  # Convert distributing sites to data.table
  dist_sites <- data.table(distributing_site = dist_sites)
  
  # Remove distributing sites from parsed content
  parsed_1$distributionProtocol.distributingSites <- NULL
  
  # Unlist the remaining parsed content
  parsed_2 <- unlist(parsed_1, recursive = FALSE)
  
  # Convert parsed content to data.table
  dt2 = as.data.table(parsed_2)
  
  # Combine data.tables
  dt_final <- cbind(dt2, dt1, dist_sites)
  
  # Clean column names
  findBiobankR::make_clean_os_names(dt_final)
  
  # Rename principal investigator columns
  nms = names(dt_final)
  nmspi <- nms[grepl("principal_investigator", nms)]
  nmspi_new <- gsub("distribution_protocol_", "", nmspi)
  setnames(dt_final, nmspi, nmspi_new)
  
  # Delete personal information columns if specified
  if (remove_personal_info) {
    personal_info <- nms[grepl("email|phone|name$", nms)]
    dt_final[, (personal_info) := NULL]
  }
  
  # Return the final data.table
  dt_final
}

