# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Execute Bulk Query
#'
#' Execute the "query" method multiple times to fetch all data by page.
#'
#' @param auth_response The authentication response obtained from `auth_os`.
#' @param query_id The saved query identifier.
#' @param driving_form The driving form for the query (default is "Specimen").
#' @param wide_row_mode Specifies whether multi-valued attributes result in a single row or one row per value (default is "OFF"). Other permitted values are SHALLOW and DEEP.
#' @param page_size Page size for each query.
#' @param max_pages Maximum number of pages to fetch.
#'
#' @return A data table containing the results of the bulk query.
#'

#' @note Make sure to provide an HTTP response with the appropriate structure for parsing.
#' @export
#' @examples
#'
#'
#' # auth_response <- auth_os(url =  Sys.getenv("OSTESTURL"),
#' #                          username = Sys.getenv("OSUSERNAME"),
#' #                          password = Sys.getenv("OSPASSWORDTEST"))
#' # 
#' # 
#' # cv_samples <- get_bulk_query(auth_response, query_id = 105)
#' #   
#' # 
#' # cv_samples[1:5]
get_bulk_query <- function(auth_response,
                       query_id,
                       driving_form = "Specimen",
                       wide_row_mode = "OFF",
                       page_size = 5000,
                       max_pages = 10000) {
  # List to store query results
  results_list <-vector(mode = "list", length = max_pages) 
  row_numbers <- vector(mode = "numeric", length = max_pages) 
  for (i in seq_len(max_pages)) {
    j = i-1
    start_at <- j * page_size
    max_results <- page_size
    
    # Execute the query for the current page
    results <- get_os_query (auth_response,
                             query_id,
                             driving_form, 
                             wide_row_mode,
                             start_at,
                             max_results)
    
    # Extract rows from the results
    rows_count <- nrow(results)
   
    
    if (!is.null(results)) {
      results_list[[i]] <- results  # Store the results in the list
      row_numbers[i] <- rows_count  # Store the number of rows retrieved
      cli::cli_alert_success(paste0(num_thousandth_sep(sum(row_numbers)),
                                    " rows retrieved"))
      
    } else {
      break  # No more data, exit the loop
    }
  }
  
  
    # Remove  0 column DFs
  results_list <- results_list[sapply(results_list, function(x) !is.null(x))]
  
   # Return the results as a single data frame
  df_results = data.table::rbindlist(results_list, fill = T) 
  
  return(df_results)
}



