# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Extract Patient ID from FindDX Aliquot ID
#'
#' This function extracts the Patient ID from FindDX Aliquot IDs.
#'
#' @param x A character vector of FindDX Aliquot IDs.
#' @return A character vector of extracted Patient IDs.
#' @export
#' 
#'
#' @examples
#'
#' get_patient_id("PP0070199910001001")
#'
get_patient_id <- function(x) {
  if (!is.character(x)) {
    stop("Input must be a character vector.")
  }
  
  if (any(nchar(x) != 18)) {
    
    warning("Some ID's do not have 18 characters. They are not standard FindDX aliquot IDs.")
    
  }
  
  patient_number <- str_extract(str_to_upper(x), "^[A-Z]{2}\\d{9}" )
  
  return(patient_number)
}

