# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get OpenSpecimen Order Detail
#'
#' This function retrieves details of a specific order from the OpenSpecimen API using the provided authentication response and order ID.
#'
#' @param auth_response The authentication response obtained from `auth_os`.
#' @param order_id The ID of the order to retrieve details for.
#' @param return_numeric Logical, whether to return timestamps as numeric values (default is TRUE). This function is parsed to parse order detail function
#' @return A data table containing the parsed order detail data.
#'
#' @importFrom httr GET status_code 
#' @export
#' @examples
#' # extract order 392 from os
#'
#' # df = get_order_detail(auth_response, order_id = 392)
#'
get_order_detail <- function(auth_response, order_id, return_numeric = F) {
  
  # Check if order_id is an integer
  if (isTRUE(round(order_id) != order_id)) {
    stop("order_id must be an integer")
  }
  
  # Extract the authentication token from the response
  auth_token <- auth_response$auth_response$token
  url <- auth_response$url
  
  # Specify the content type as JSON in the header
  headers <- add_headers(
    "Content-Type" = "application/json",
    "X-OS-API-TOKEN" = auth_token
  )
  
  # Construct the URL for the order detail
  order_url <- paste0(url, "/distribution-orders/", order_id)
  
  # Make the GET request for the order detail
  response <- GET(
    url = order_url,
    config = headers,
    encode = "json"
  )
  
  
  results <- parse_os_response(response,
                               parse_data_function = "parse_order_detail_data",
                               return_numeric = return_numeric)
  
  if(inherits(results, "data.frame")) {
    
    return(results)
    
  }else {
    
    return(NULL)
  }
  
}

