# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get OpenSpecimen Orders in Bulk
#'
#' This function retrieves a list of orders from the OpenSpecimen API in bulk, handling pagination and combining results. It uses the provided authentication response and optional query parameters for customization.
#'
#' @param auth_response The authentication response obtained from `auth_os`.
#' @param include_stats Logical, whether to include statistics (default is TRUE).
#' @param page_size Integer, the number of results to retrieve per page (default is 250).
#' @param max_pages Integer, the maximum number of pages to retrieve (default is 10,000).
#'
#' @return A data frame containing the aggregated order data from multiple pages.
#'

#' @importFrom httr GET add_headers status_code
#'
#' @note This function allows you to efficiently retrieve orders from OpenSpecimen in bulk while handling pagination and result aggregation.
#'
#' @export
#' @examples
#' #get_bulk_orders()
get_bulk_orders <- function(auth_response, 
                            include_stats = TRUE, 
                            page_size = 250,
                            max_pages = 10000) {
  
  # List to store query results
  results_list <-  vector(mode = "list", length = max_pages)
  row_numbers <- vector(mode = "numeric", length = max_pages) 
  
  for (i in  seq_len(max_pages)) {
    j = i - 1
    start_at <- j * page_size
    max_results <- page_size
    
    results <- get_orders(auth_response, include_stats, start_at, max_results)
    
    rows_count <- nrow(results)
    
    if (rows_count > 0) {
      
      results_list[[i]] <- results  # Store the results in the list
      row_numbers[i] <- rows_count  # Store the number of rows retrieved
      cli::cli_alert_success(paste0(num_thousandth_sep(sum(row_numbers)),
                                    " rows retrieved"))
      
    } else {
      
      break  # No more data, exit the loop
    }
  }
  
  # Remove 0-column data frames
  results_list <- results_list[sapply(results_list, function(x) !is.null(x))]
  
  # Return the results as a single data frame
  df_results = data.table::rbindlist(results_list, fill = TRUE) 
  
  return(df_results)
}

