# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get OpenSpecimen Orders
#'
#' This function retrieves a list of orders from the OpenSpecimen API using the provided authentication response and optional query parameters.   https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/259457077/Retrieve+list+of+Orders

#'
#' @param auth_response The authentication response obtained from `auth_os`.
#' @param include_stats Logical, whether to include statistics (default is TRUE).
#' @param start_at Integer, the starting position for pagination (optional).
#' @param max_results Integer, the maximum number of results to retrieve (optional).
#'
#' @return A data frame containing the parsed order data.
#'
#' @importFrom httr GET add_headers status_code
#' @note This function allows you to retrieve orders from OpenSpecimen and parse the response data into a data frame.   https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/259457077/Retrieve+list+of+Orders

#'
#' @export
#' @examples
#' #get_orders()
get_orders <- function(auth_response, 
                       include_stats = TRUE, 
                       start_at = NULL, 
                       max_results = NULL) {
  # Create the request object
  auth_token <- auth_response$auth_response$token
  url <- auth_response$url
  query_request <- list(includeStats = include_stats, 
                        startAt = start_at,
                        maxResults = max_results)
  
  # Specify the content type as JSON in the header
  headers <- add_headers(
    "Content-Type" = "application/json",
    "X-OS-API-TOKEN" = auth_token
  )
  
  # Make the GET request for the orders
  response <- GET(
    url = paste0(url,"/distribution-orders"),
    query = query_request,
    config = headers
  )
  
  
  parse_os_response(response, parse_data_function = "parse_os_order_data")
  
  
}

