# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand


#' Retrieve Order Items from OpenSpecimen
#'
#' This function retrieves the details of order items of the requested order from OpenSpecimen.
#'
#' @param auth_response Authentication response from OpenSpecimen.
#' @param order_id ID of the order whose items are requested.
#'
#' @return A data.table containing parsed information from the OpenSpecimen order items.
#'
#' @importFrom httr GET add_headers
#' @export
#' @examples
#' #get_order_items()
get_order_items <- function(auth_response, order_id) {
  
  if (isTRUE(round(order_id) != order_id)) {
    stop("order_id must be an integer")
  }
  
  # Extract the authentication token from the response
  auth_token <- auth_response$auth_response$token
  url <- auth_response$url
  
  # Specify the content type as JSON in the header
  headers <- add_headers(
    "Content-Type" = "application/json",
    "X-OS-API-TOKEN" = auth_token
  )
  
  # Make the GET request for the query
  response <- GET(
    url = paste0(url, "/distribution-orders/", order_id, "/items"),
    config = headers,
    encode = "json"
  )
  
  # Parse the response and return the results
  results <- parse_os_response(response,
                               parse_data_function = "parse_os_oder_list")
  
  # If inherits data.frame, return results, else return NULL
  if (inherits(results, "data.frame")) {
    return(results)
  } else {
    return(NULL)
  }
}
