# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Get the specimen type ID from a Aliquot ID.
#'
#' This function extracts the specimen type ID from a Aliquot ID.
#'
#' @param x A character vector representing Aliquot IDs.
#'
#' @return A character vector of specimen type IDs.
#'
#' @importFrom stringr str_sub
#'
#' @export
#' @examples
#'
#' get_specimen_type_id("PP0070199910001001")
#'
get_specimen_type_id <- function(x) {
  if (!is.character(x)) {
    stop("Input must be a character vector.")
  }
  
  if (any(nchar(x) != 18)) {
    
    warning("Some ID's are not standard FindDX aliquot ID.")
 
  }
  
  specimen_type_id <- str_sub(x, 14, 15)
  
  return(specimen_type_id)
}


