# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get Orders
#'
#' Use this function to retrieve distribution orders in the OpenSpecimen application.
#' The function sends an HTTP GET request to the OpenSpecimen server to fetch details of distribution orders.
#'
#' @param auth_response Authentication response object obtained from the OpenSpecimen API.
#' @param include_stats If TRUE, includes statistics in the response (optional, default is TRUE).
#' @param start_at Starting row of the result (optional).
#' @param max_results Maximum number of records to fetch (optional).
#'
#' @return A data frame containing the details of distribution orders, or NULL if an error occurs.
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' auth_response <- authenticate_user(username = "your_username", password = "your_password")
#' orders <- get_orders(auth_response)
#' }
#'
#' #get_orders()
#' @seealso \code{\link{auth_os}}, \code{\link{parse_os_response}}, \code{\link{parse_os_order_data}}
#'
#' @export
get_orders <- function(auth_response, include_stats = TRUE, start_at = NULL, max_results = NULL) {
  
  # URL to get distribution orders
  # For more details, refer to: https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/1115667/Get+Distribution+Orders
  url <- paste0(auth_response$url, "/distribution-orders")
  
  # Specify the content type as JSON in the header
  headers <- httr::add_headers(
    "Content-Type" = "application/json",
    "X-OS-API-TOKEN" = auth_response$auth_response$token
  )
  
  # Construct query parameters based on provided arguments
  query_params <- list(
    includeStats = include_stats,
    startAt = start_at,
    maxResults = max_results
  )
  
  # Remove NULL parameters
  query_params <- query_params[!sapply(query_params, is.null)]
  
  # Append query parameters to the URL
  if (length(query_params) > 0) {
    url <- httr::modify_url(url, query = query_params)
  }
  
  # Make the GET request for the orders
  response <- httr::GET(url = url, config = headers)
  
  # Parse the response and return the results
  results <- parse_os_response(response, parse_data_function = "parse_os_order_data")
  
  # If inherits data.frame, return results, else return NULL
  if (inherits(results, "data.frame")) {
    return(results)
  } else {
    return(NULL)
  }
}



