# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Get Bulk OpenSpecimen Order Details
#'
#' This function retrieves details for a bulk list of orders from the OpenSpecimen API using the provided authentication response and order IDs.
#'
#' @param auth_response The authentication response obtained from `auth_os`.
#' @param orders_ids A vector of order IDs for which details are to be retrieved.
#' @param ... Additional parameters to be passed to `get_order_detail`.
#'
#' @return A data.table containing the parsed details for the specified orders.
#'
#' @export
#' @examples
#' #get_bulk_order_detail()
get_bulk_order_detail <- function(auth_response, orders_ids, ...) {
  
  # Check if orders_ids is a vector of integers
  if (isTRUE(any(round(orders_ids) != orders_ids))) {
    stop("orders_ids must be an integer")
  }
  
  # Convert lapply to a for loop and print after every 100 iterations
  # Use tryCatch to handle errors
  
  list_dfs <- vector("list", length(orders_ids))
  
  for (i in seq_along(orders_ids)) {
    
    list_dfs[[i]] <- tryCatch(
      get_order_detail(order_id = orders_ids[i], auth_response, ...),
      error = function(e) {
        cli::cli_alert_warning(paste0("Error in order_id: ", orders_ids[i], " ", e$message))
        return(NULL)
      }
    )
    
    if (i %% 100 == 0) {
      cli::cli_alert_success(
        paste0("Retrieved ", i, " orders",
               " out of ", length(orders_ids))
      )
    }
  }
  
  ## Combine the list of data.tables into a single data.table
  dt_final = data.table::rbindlist(list_dfs, fill = TRUE)
  
  cli::cli_alert_success(paste0("All ", i, " orders retrieved"))
 # timestamp_to_date.data.frame(dt_final, return_numeric = TRUE)
  return(dt_final)
  
}

