# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Retrieve Order Items for Multiple Orders
#'
#' This function retrieves order items for multiple orders specified by their IDs.
#'
#' @param auth_response Authentication response obtained from the OpenSpecimen API.
#' @param orders_ids Vector of integers representing the IDs of the orders to retrieve items for.
#' @param ... Additional parameters to be passed to `get_order_items` function.
#'
#' @return A data.table containing the retrieved order items.
#'
#' @examples
#' \dontrun{
#' auth_response <- auth_os(url, username, password)
#' orders_data <- get_bulk_order_items(auth_response, c(1, 2, 3))
#' }
#'
#' #get_bulk_order_items()
#' @export
get_bulk_order_items <- function(auth_response, orders_ids, ...) {
  
  # check orders_ids is a vector of integers
  if(isTRUE(any(round(orders_ids) != orders_ids))) {
    stop("orders_ids must be an integer")
  }
  
  # use tryCatch to handle errors
  
  list_dfs <- vector("list", length(orders_ids))
  
  for (i in seq_along(orders_ids)) {
    
    list_dfs[[i]] <- tryCatch(
      get_order_items(auth_response, order_id = orders_ids[i], ...),
      error = function(e) {
        cli::cli_alert_warning(paste0("Error in order_id: ", orders_ids[i], " ", e$message))
        return(NULL)
      }
    )
    
    if (i %% 10 == 0) {
      cli::cli_alert_success(
        paste0("Retrieved ", i, " orders",
               " out of ", length(orders_ids))
      )
    }
  }
  
  ## combine the list of data.tables into a single data.table
  dt_final = data.table::rbindlist(list_dfs, fill = TRUE)
  
  cli::cli_alert_success(paste0("Done: orders retrieved"))
  
  return(dt_final)
  
}

