# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Get the event ID from a Aliquot ID.
#'
#' This function extracts the event ID from a Aliquot ID.
#'
#' @param x A character vector representing Aliquot IDs.
#'
#' @return A character vector of event IDs.
#'
#'
#' @importFrom stringr str_sub
#'
#' @export
#' @examples
#'
#' get_event_id("PP0070199910001001")
#'


get_event_id <- function(x) {
  if (!is.character(x)) {
    stop("Input must be a character vector.")
  }
  
  if (any(nchar(x) != 18)) {
    warning("Some ID's are not a standard FindDX aliquot ID.")
 
  }
  
  event_id <- str_sub(x, 12, 13)
  
  return(event_id)
}


