# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Clean Open Specimen Names
#' 
#' @description
#' Data set from Open specimen normally come with very programming unfriendly column
#' names with repeat suffixes # and so on this function attempts to correct this
#' 
#' @param names_os_df column names from Open specimen data
#' @importFrom stringr str_trim str_split
#' @importFrom janitor make_clean_names
#' @return A character vector of names
#' 
#' @export
#' @examples
#'
#' nms_os <- c("Participant_PPID", "Visit_Visit Site",
#'             "Visit_Name", "Visit_Event Label", 
#'             "Specimen_Specimen Label",
#'             "Specimen_Type", "Specimen_Lineage", "Specimen_Barcode", 
#'             "Specimen_Container Name", "Specimen_Container Position", 
#'             "Specimen_Requirement Name", "Collection Protocol_Short Title")
#'
#' make_clean_os_names(nms_os)
make_clean_os_names <- function(names_os_df){
   
   
  nms_break = make_clean_names(names_os_df) %>%
    str_trim

  
  split_nms <- lapply(nms_break,  str_split, "_")
  
  new_names <- vector(mode = "character",
                      length = length(nms_break))
  
  
  
  for(i in 1:length(split_nms)){
    
    this_s = split_nms[[i]] %>% unlist()
    tru_same = this_s[1] == this_s[2]
    
    if(tru_same& length(this_s) >= 2){
      
      this_s = this_s[-1]
    }
    
    this_s = paste0(this_s, collapse = "_")
    new_names[i] = this_s
  }
  
  
  new_names
}
