# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Mark All Duplicates in a Vector
#'
#' This function identifies all duplicate elements in a vector, marking both the first
#' occurrence and subsequent duplicates.
#'
#' @param vec A numeric or character vector where duplicates are to be identified.
#'
#' @return A logical vector of the same length as `vec`, where TRUE indicates that
#' the corresponding element in `vec` is a duplicate.
#'
#' @export
#' @examples
#'
#' vec <- c("apple", "banana", "apple", "cherry", "banana")
#' mark_all_duplicates(vec)
mark_all_duplicates <- function(vec) {
  # Check duplicates from the start and from the end
  dup_from_start <- duplicated(vec)
  dup_from_end <- duplicated(vec, fromLast = TRUE)
  
  # Combine the two to mark all duplicates (including first occurrences)
  all_duplicates <- dup_from_start | dup_from_end
  return(all_duplicates)
}

