# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Format Numeric Values with Thousands Separator
#'
#' This function takes a numeric atomic vector `x` and formats the values with a thousands separator using `scales::label_comma()`. If the input `x` is not a numeric atomic vector, it will throw an error.
#'
#' @param x A numeric atomic vector to be formatted with a thousands separator.
#' @param sep The character used as the thousands separator (default is a comma).
#' @return A character vector with formatted numeric values.
#' @note This function is useful for formatting numeric values in a human-readable format.
#'
#' @export
#' @examples
#'
#' num_thousandth_sep(100)
#' num_thousandth_sep(1234567)
#' num_thousandth_sep(c(1234, 5678, 9876))
#'
num_thousandth_sep <- function(x, sep = ",") {
  
  if (!is.numeric(x)) {
    
    stop("Input is not a numeric  vector.")
    
  } else {
    
    return(scales::label_comma(big.mark = sep)(x))
    
  }
  
}

