# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Clean Numeric Values
#'
#' Use this function to clean numeric values from Excel (.xlsx) or Salesforce report date,
#' where missing values are presented with a dash ("-").
#'
#' The function removes commas and dashes from the input character vector and converts
#' it to a numeric vector.
#'
#' @param x A character vector containing numeric values with potential commas and dashes.
#'
#' @return A numeric vector after cleaning the input values.
#'
#' @export
#' @examples
#' x <- c("1,000", "2,000", "3,000", "4,000",
#'       "5,000", "-", "7,000",
#'       "8,000","-", "10,000")
#'
#' nums_clean(x)
nums_clean <- function(x) {
  
  # Remove commas and dashes from the input character vector
  x <- gsub(",|-", "", x)
  
  # Convert the cleaned character vector to numeric
  as.numeric(x)
  
}

