# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' OpenSpecimen API Request Response Handler
#'
#' This function handles the response from an OpenSpecimen API request, checks the status code,
#' and returns the parsed response content or handles errors as needed.
#'
#' @param response The response object from the OpenSpecimen API request.
#' @param parse_data_function The function used to parse the response data
#'
#' @return Parsed content from the API response.
#'
#' @importFrom httr status_code content
#'
#' @export
#' @examples
#' #parse_os_response()
parse_os_response <- function(response, parse_data_function) {
  
  

    status_code <- status_code(response)
    
    if (status_code == 200) {
      # Query successful, return the parsed response content
      parse_data_function <- match.fun(parse_data_function)
      #cli::cli_alert_success("Query successful")
      return(parse_data_function(response))
      
    } else {
      # Query failed, return an error message or handle it as needed
      error_message <- content(response, "text")
      error_message <- gsub("[^a-zA-Z0-9 ]", " ", error_message)
      error_message <- sub(".*\\bmessage\\s*(.*)", "\\1", error_message, ignore.case = TRUE)
      stop(paste("Query failed with status code", status_code, ":", error_message))
      
    }
 
  
}

