# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Parse OpenSpecimen Site Details
#'
#' Use this function to parse the response and extract details of a site from the OpenSpecimen application.
#'
#' @param response The API response object.
#'
#' @return A data table containing the parsed details of the site.
#'
#' @export
#' @examples
#' #parse_site_details()
parse_site_details <- function(response) {
  
  # Extract the content from the response
  mycontent2 <- content(response, "parsed")
  
  # Extract extension details
  extension_details <- mycontent2$extensionDetail
  
  # Extract attribute details
  attr_dp <- extension_details$attrs
  
  # Create clean column names
  col_nms <- sapply(attr_dp, function(x) x$caption) %>% 
    janitor::make_clean_names()
  
  # Extract attribute values
  values <- lapply(attr_dp, function(x) x$value)
  
  # Set names for values
  names(values) <- col_nms
  
  # Convert values to data.table
  dt1 = as.data.table(values)
  
  # Remove extension details from parsed content
  mycontent2$extensionDetail <- NULL
  mycontent2$coordinators <- NULL
  # Convert remaining parsed content to data.table
  mycontentdf <- mycontent2 %>% as.data.table()
  
  # Combine data.tables
  mycontentdf <- cbind(mycontentdf, dt1)
  
  # Return the final data.table
  mycontentdf
  
}

