# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Parse OpenSpecimen Order Item List
#'
#' This function parses a list of OpenSpecimen order items list (distributed samples) and returns a data.table with selected fields.
#'
#' @param response Response object from httr::GET [Link to Api details](https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/259457102/Retrieve+Order+Items)
#'
#' @return A data.table containing parsed information from the OpenSpecimen order items.
#' @importFrom httr content
#' @importFrom data.table rbindlist as.data.table
#' @note  [Link to Api details](https://openspecimen.atlassian.net/wiki/spaces/CAT/pages/259457102/Retrieve+Order+Items)
#' @export
#' @examples
#'
#' #parse_os_oder_list(oder_items)
#'
parse_os_oder_list <- function(response) {
  
  oder_items <- content(response, "parsed")
  nms <- c("orderId", "orderName", "status", 
           "specimen.ppid", "specimen.label",
           "specimen.eventLabel",
           "specimen.cpShortTitle", 
           "specimen.visitDate",
           "specimen.type",
           "specimen.availabilityStatus")
  
  df_list <- lapply(seq_along(oder_items), function(x) {
    
    list_x = oder_items[[x]]
    
    vec_unlist <- unlist(list_x, recursive = TRUE)
    nms_all = names(vec_unlist)
    nms <- nms[nms %in% nms_all]
    vec_unlist[nms] %>% as.list() %>% 
      as.data.table()
    
  })
  
  dt <- rbindlist(df_list, fill = TRUE)
  
  make_clean_os_names(dt)
  
  return(dt)
  
}

