# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Parse All Sites
#'
#' Use this function to parse the response content from the OpenSpecimen API
#' and extract the details of all sites.
#'
#' @param response The response object obtained from the OpenSpecimen API.
#'
#' @return A data frame containing the details of all sites.
#'
#' @export
#' @examples
#' #parse_all_sites()
parse_all_sites <- function(response) {
  
  # Extract the content from the response
  mycontent <- content(response, "parsed")
  
  # Extract the sites from the content
  df <- lapply(mycontent, as.data.table) %>%
    rbindlist(fill = TRUE)
  
  # Return the sites
  return(df)
  
}

