# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' OpenSpecimen API Request Response Handler
#'
#' This function handles the response from an OpenSpecimen API request, checks the status code,
#' and returns the parsed response content or handles errors as needed.
#'
#' @param response The response object from the OpenSpecimen API request.
#' @param parse_data_function The function used to parse the response data
#' @param skip_date_convertion Skip date conversion
#' @param ... Additional arguments to be passed to timestamp_to_date
#' @return Parsed content from the API response.
#'
#' @importFrom httr status_code content
#'
#' @export
#' @examples
#' #parse_os_response()
parse_os_response <- function(response, parse_data_function, skip_date_convertion = FALSE, ...) {
  
  
  
  status_code <- status_code(response)
  
  if (status_code == 200) {
    # Query successful, return the parsed response content
    parse_data_function <- match.fun(parse_data_function)
    #cli::cli_alert_success("Query successful")
    df = parse_data_function(response)
    
    # if inherits data.frame apply timestamp_to_date
    
    if(inherits(df, "data.frame") & !skip_date_convertion){
      
     df = rm_all_na_col(df)
     df =  timestamp_to_date(df, ...)
     
    }
    
    return(df)
    
  } else {
    # Query failed, return an error message or handle it as needed
    error_message <- content(response, "text")
    error_message <- gsub("[^a-zA-Z0-9 ]", " ", error_message)
    error_message <- sub(".*\\bmessage\\s*(.*)", "\\1", error_message, ignore.case = TRUE)
    stop(paste("Query failed with status code", status_code, ":", error_message))
    
  }
  
  
}

