# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Parse Response Data
#'
#' This function parses the response data obtained from the OpenSpecimen API and
#' organizes it into a data frame.
#'
#' @param response The response data to be parsed.
#'
#' @return A data frame containing the parsed data.
#'
#' @importFrom httr content
#'
#'
#' @note Make sure to provide an HTTP response with the appropriate structure for parsing.
#'
#' @export
#' @examples
#' #parse_data()
parse_data <- function(response) {
  
  # Parse the content from the response
  parsed_content_request <- content(response, as = "parsed")
  
  # Extract column names from the parsed content
  col_nms <- parsed_content_request$columnLabels %>% unlist()
  
  # Clean and format column names
  col_nms <- gsub("#", "", col_nms) %>% findBiobankR::make_clean_os_names()
  
  # Extract rows from the parsed content
  myrows <- parsed_content_request$rows
  n_rows <- length(myrows)
  # Create a data frame from the rows
  if(n_rows != 0 ) {
    
    df <- lapply(myrows, function(x) {
      rbind(x)
    }) %>%
      data.table::rbindlist()
    
    if(ncol(df) > 0){
      
      names(df) <- col_nms
    }
    
  } else {
    
    df <- NULL
  }
  
  
  return(df)
  
}

