# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Save selected aliquots as excel
#' 
#' Save the selected aliquots with the check column data set in excel 
#'
#' @param file_path The location to save your file as .xlsx
#' @param save_file Logical to save file in 
#' @param ...  arguments taken by findBiobankR::append_check_col
#' @importFrom tools file_ext
#' @importFrom openxlsx write.xlsx
#' @return A data frame silently writes a file to given path
#' 
#' @export
#' @examples
#'
#' library(data.table)
#' library(dplyr)
#' data("tb_data", package = "findBiobankR")
#' #data("tb_specimen_df", package = "findBiobankR")
#'
#' # required clinical cols
#' clinical_cols <- c("tb_group", "hiv_status", "sex", "country") 
#'
#' clin_specs  <- convert_os_df_to_wide(clinical_df = tb_data,
#'                                      specimen_df = tb_specimen_df, 
#'                                      join_by_col = "ppid",
#'                                      specimen_col ="specimen_type" ,
#'                                      clinical_vars = clinical_cols ,
#'                                      specimen_label_col = "specimen_label",
#'                                      os_aliquot_names = c("Serum", "Plasma")
#' )
#'
#'
#' clin_specs[, serum_aliquot := select_one_aliquot(NP_labels_serum, aliquot_number = 1 )]
#' clin_specs[, plasma_aliquot := select_one_aliquot(NP_labels_plasma, aliquot_number= 1 )]
#'
#'
#' selected_samples <- selected_aliquots_df(clin_specs,
#'                                          aliquot_cols = c("serum_aliquot","plasma_aliquot"),
#'                                          ppid_col = "ppid")
#'
#' path_name <- tempfile(pattern = "create_work_book") %>%
#'   normalizePath(winslash = "/")
#'
#' dir.create(path_name)
#'
#' # create file name
#' path_name <- file.path(path_name, "aliquots.xlsx")
#'
#' process_save_selected_aliquots(file_path = path_name,
#'                                save_file= TRUE,
#'                                selected_samples = selected_samples,
#'                                os_position = tb_specimen_df,
#'                                ppid_col = "ppid",
#'                                specimen_id_col = "specimen_label",
#'                                os_required_cols = c("ppid",
#'                                                     "Specimen_Specimen Label",
#'                                                     "Specimen_Type",
#'                                                     "Specimen_Requirement Name", 
#'                                                     "Specimen_Barcode",
#'                                                     "Specimen_Container Name", 
#'                                                     "Specimen_Container Position",
#'                                                     "Scanned_barcode"))
#'

process_save_selected_aliquots <- function(file_path = NULL, save_file= FALSE, ...){
  
  if(!is.null(file_path)){
    
    stopifnot( "save_file option should be TRUE when file_path is provided" = isTRUE(save_file))
    dir_name = dirname(file_path)
    
    if(isFALSE(dir.exists(dir_name))) {
      
      stop(sprintf("The folder (%s) does not exist, Please check you file path", dir_name))
    } 
    
    file_extension = file_ext(file_path)
    
    if(file_extension != "xlsx"){
      
      stop("The extension of the file is not an excel file")
      
    }
    
    
  }
  
  
  selected_aliquots <- append_check_col(...)
  
  
  
  
  stopifnot("save_file option should be logical" = isTRUE(is.logical(save_file)))
  
  if(isFALSE(save_file)){
    
    message(sprintf("File not save. if you want to save please provide arguments file_path and save_file should be true"))
    
  }
  
  if(save_file){
    message(sprintf("Saving the selected data frame in %s", file_path))
    write.xlsx(selected_aliquots,
               file = file_path ) 
  }
  
  return(selected_aliquots)
  
}
