# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Read Sheets  From excel workbook
#' 
#' Read Files From excel workbook 
#' 
#' @param file_path path to file  
#' @param ... Other parameters from read excel function 
#' @return returns a list of data frames 
#' @importFrom readxl read_excel excel_sheets
#' @importFrom data.table setDT 
#' @importFrom purrr  set_names possibly
#' @importFrom tools file_ext
#' @importFrom janitor make_clean_names
#' @return A list of data frames 
#' 
#' @export
#'
#' @examples
#' iris_species <- system.file("extdata", "iris_species.xlsx",
#'                           package = "findBiobankR")
#'
#' iris_list <- read_multiple_sheets(file_path  = iris_species ) %>% 
#'   lapply(head, 4)
#' iris_list
read_multiple_sheets <- function(file_path, ...){
    
    
    if(isFALSE(file.exists(file_path))) {
        
        stop("The file provided doesn't exists, Check path")
    } 
    
    file_extension = file_ext(file_path)
    
    if(file_extension != "xlsx"){
        
        stop("The extension of the file is not an excel file")
        
    }
    
    xl_sheets <- excel_sheets(file_path)
    
    xl_sheets_clean <- make_clean_names(xl_sheets)
    
    possi_excel <- possibly(read_excel, otherwise = NULL)
    
    list_of_files <- lapply(xl_sheets, function(x){
        
        possi_excel(file_path, sheet = x, ...) %>%

      setDT()
        
    })%>% set_names(xl_sheets_clean)
    
   
    
}
