# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Read multiple files from a folder
#' 
#' Read Files From excel workbook 
#' 
#' @param folder_path path to file  
#' @param ... Other parameters from read function used 
#' @param read_function The read function eg read.csv, 
#' read_excel, fread. Depends on your file types or function preference. 
#' Please note to load the library you want to use the function from
#' @param pattern A pattern to be passed to list.files function
#' @param file_names If you have a vector of file names then this could also be used instead of pattern
#' @return returns a list of data frames 
#' @importFrom data.table setDT 
#' @importFrom purrr  set_names possibly
#' @importFrom tools file_ext
#' @importFrom janitor make_clean_names
#' @return A list of data frames 
#' 
#' @export
#'
#' @examples
#' iris_species <- system.file("extdata", "iris_species.xlsx",
#'                           package = "findBiobankR")
#'
#' iris_list <- read_multiple_sheets(file_path  = iris_species ) %>% 
#'   lapply(head, 4)
#' iris_list
#'

#' library(data.table)
#' iris_split <- split(iris, 
#'                     f = iris$Species)
#'
#'
#' path_name <- tempfile(pattern = "read_multipe_files") %>%
#'     normalizePath(winslash = "/")
#'
#' dir.create(path_name)
#' file_names <- paste0(names(iris_split),  ".csv")
#' # create file name
#' file_paths <- file.path(path_name, file_names)
#' lapply(seq_along(file_paths), function(x){
#'     df = iris_split[[x]]
#'     fwrite(df, file = file_paths[x])
#' })
#'
#' read_multiple_files(folder_path =path_name ,
#'                     read_function = "fread",
#'                     pattern = ".csv$",
#'                     file_names =NULL)
#' #file.remove(file_name)
#' unlink(path_name)
read_multiple_files <- function(folder_path,
                                read_function = "fread",
                                pattern = NULL,
                                file_names = NULL,
                                ...){
  
  
  if(isFALSE(dir.exists(dirname(folder_path)))) {
    
    stop("The directory provided doesn't exists, Check path")
  } 
  
  if(is.null(pattern) & is.null(file_names)){
    
    stop("Please provide a pattern or a vector of file names")
  }
  
  if(!is.null(pattern) & !is.null(file_names)){
    
    stop("Please provide  pattern or a vector of file names")
  }
  if(!is.null(pattern) & is.null(file_names)){
    
    if(length(pattern) != 1){
      
      stop("Pattern should be of length one")
    }
    
    file_names = list.files(path = folder_path, pattern = pattern )
    
    if(length(file_names) == 0){
      
      
      stop("No files found with the pattern provided. Please check ypur pattern and folder")
    }
    
    file_paths = file.path(folder_path, file_names)
    
  }else{
    
    file_paths = file.path(folder_path, file_names)
  }
  
  extesions = tools::file_ext(file_names) %>%
    unique()
  
  stopifnot("Your files are of different types" = length(extesions) == 1)
  
  files_exits <- file_paths %>%
    purrr::map_lgl(file.exists)
  
  if(!all(files_exits)){
    
    files_missing =  file_names[!files_exits] %>%
      paste0(collapse = " , ")
    warn_msg <- sprintf("The following files %s have not been found", files_missing)
    warning(warn_msg)
  }
  read_function = match.fun(read_function)
  
  
  file_names_clean <- make_clean_names(file_names)
  
  possibly_read <- possibly(read_function, otherwise = NULL)
  
  list_of_files <- lapply(file_paths, function(x){
    
    possibly_read(x,  ...) %>%
      
      setDT()
    
  })%>% set_names(file_names_clean)
  
  list_of_files
  
  
}

