# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Group By Vector Elements and Count Frequencies
#'
#' This function takes a data frame, a vector of column names (`myvec`), and a vector of grouping 
#' column names (`byvec`). It then groups the data frame by each element in `myvec` along with the 
#' specified grouping columns (`byvec`). For each group, it counts the frequencies of non-empty 
#' and non-missing values in the specified column (`myvec_i`) and returns a summary data frame.
#'
#' @param df The input data frame.
#' @param myvec A vector of column names to be used for grouping and counting frequencies.
#' @param byvec A vector of column names for grouping the data frame. ID columns that don't change
#'
#' @return A data table summarizing the frequencies of non-empty and non-missing values in 
#' each group for the specified columns.
#'
#'
#' @export
#' @examples
#' #groupby_vec()
groupby_vec <- function(df, myvec, byvec) {
    # Use lapply to iterate over myvec
    list_dfs <- lapply(myvec, function(myvec_i) {
        # Combine grouping columns with the current myvec element
        byvec2 <- c(byvec, myvec_i)
        
        # Group by specified columns and count frequencies
        specs <- df[get(myvec_i) != "" | !is.na(get(myvec_i)), 
                    list(freq = .N), by = byvec2]
        
        # Rename the column representing myvec element to "variable"
        setnames(specs, myvec_i, "variable")
        
        # Add a new column to store the original column name (myvec element)
        specs[, col_name := myvec_i]
        
        # Return the summarized data frame
       specs
    })
    
    # Combine the list of data frames into a single data frame
    mydf <- data.table::rbindlist(list_dfs, fill = TRUE)
    
    # Return the summarized data frame
    mydf
}


#' Remove Form Name Prefix from Data Frame Column Names 
#'
#' This function removes a specified form name prefix from the column names of a data frame. Usually from Open specimen
#'
#' @param df Data frame whose column names need to be modified.
#' @param form_name Prefix to be removed from the column names. Default is "participant_additional_fields_tb_c_ps_".
#'
#' @return A modified data frame with the specified form name prefix removed from column names.
#'
#' @examples
#' \dontrun{
#' # Assuming df is a data frame with column names like "participant_additional_fields_tb_c_ps_Field1"
#' df_modified <- rm_form_name(df)
#' }
#'
#' #rm_form_name()
#' @export
rm_form_name <- function(df, form_name = "participant_additional_fields_tb_c_ps_") {
  
  nms <- names(df)
  nms_new <- gsub(form_name, "", nms)
  setnames(df, nms, nms_new)
  
  return(df)
  
}

