# WARNING - Generated by {fusen} from dev/biobank_reports.Rmd: do not edit by hand

#' Remove Form Name Prefix from Data Frame Column Names 
#'
#' This function removes a specified form name prefix from the column names of a data frame. Usually from Open specimen
#'
#' @param df Data frame whose column names need to be modified.
#' @param form_name Prefix to be removed from the column names. Default is "participant_additional_fields_tb_c_ps_".
#'
#' @return A modified data frame with the specified form name prefix removed from column names.
#'
#' @examples
#' \dontrun{
#' # Assuming df is a data frame with column names like "participant_additional_fields_tb_c_ps_Field1"
#' df_modified <- rm_form_name(df)
#' }
#'
#' #rm_form_name()
#' @export
rm_form_name <- function(df, form_name = "participant_additional_fields_tb_c_ps_") {
  
  nms <- names(df)
  nms_new <- gsub(form_name, "", nms)
  setnames(df, nms, nms_new)
  
  return(df)
  
}

