# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Create a data frame with selected aliquots in long format
#'
#' @description
#' This function is used in conjunction from other findBiobankR package. It accepts an a data drame/data.table 
#' with selected aliquots as a column 
#' @seealso findBiobank::select_one_aliquot
#' @param clin_specs A data from with the selected aliquots as column
#' @param aliquot_cols Column names of the selected aliquots in `clin_specs` data frame
#' @param ppid_col Participant ID column 
#' @param aliquot_name_col The name of the variable name after data.table::melt
#' @param spec_label_col The name of the value name after data.table::melt
#' @importFrom stringr str_replace_all str_trim
#' @importFrom data.table melt setDT
#' @return a data.table with `ppid, specimen_label_col` columns 
#' 
#' @export
#' 
#' @examples
#'
#' library(data.table)
#' library(dplyr)
#' data("tb_data", package = "findBiobankR")
#' data("tb_specimen_df", package = "findBiobankR")
#'
#' # required clinical cols
#' clinical_cols <- c("tb_group", "hiv_status", "sex", "country") 
#'
#' clin_specs  <- convert_os_df_to_wide(clinical_df = tb_data,
#'                                      specimen_df = tb_specimen_df, 
#'                                      join_by_col = "ppid",
#'                                      specimen_col ="specimen_type" ,
#'                                      clinical_vars = clinical_cols ,
#'                                       specimen_label_col = "specimen_label",
#'                                      os_aliquot_names = c("Serum", "Plasma")
#' )
#'
#'
#' clin_specs[, serum_aliquot := select_one_aliquot(NP_labels_serum, aliquot_number = 1 )]
#' clin_specs[, plasma_aliquot := select_one_aliquot(NP_labels_plasma, aliquot_number= 1 )]
#'
#' ## prepare data set
#' selected_aliquots_df(clin_specs,
#'                      aliquot_cols = c("serum_aliquot","plasma_aliquot"),
#'                      ppid_col = "ppid")
selected_aliquots_df <- function(clin_specs,
                                 aliquot_cols,
                                 ppid_col = "Participant_PPID",
                                 aliquot_name_col = "aliquot_name",
                                 spec_label_col = "specimen_label"){
  
  
  data_name = deparse(substitute(clin_specs))
  
  if(isFALSE(inherits(clin_specs, "data.table"))){
    
    msg = sprintf("%s is a data.frame converting this to data.table", data_name)
    message(msg)
  }
  nms_selected_labels <- c(ppid_col,aliquot_cols)
  
  urien23selected <- clin_specs[, .SD, .SDcols = nms_selected_labels]
  
  
  
  urien23selected_m <- melt(urien23selected, 
                            id.vars =ppid_col,
                            variable.name = aliquot_name_col,
                            value.name = spec_label_col)
  
  urien23selected_m[, (aliquot_name_col) := NULL]
  
  urien23selected_m <- urien23selected_m[!is.na(get(spec_label_col))]
  
  urien23selected_m <- unique(urien23selected_m,
                              by ="specimen_label")
  urien23selected_m[, (spec_label_col) := str_replace_all(get(spec_label_col), '"|\\)|\\(|^c', '')]
  urien23selected_m[, (spec_label_col) := str_trim(get(spec_label_col))]
  urien23selected_m
}
