# WARNING - Generated by {fusen} from /dev/sample_selections.Rmd: do not edit by hand

#' Title Select many aliquots 
#'
#' Description Selects multiple aliquots labels from a list of lists.
#'
#' @param x A list of lists containing aliquot labels.
#' @param aliquots The number of aliquots to select.
#'
#' @return A list of vectors, each containing the selected aliquot labels.
#'
#' @export

#' @examples
#' 
#' samples_list <- list(c("TB0990100010101001", "TB0990100010101002", "TB0990100010101003"),
#'                      c("TB0990100020101001", "TB0990100020101002", "TB0990100020101003"), 
#'                      c("TB0990100030101001", "TB0990100030101002", "TB0990100030101003"),
#'                      c("TB0990100040101001", "TB0990100040101002", "TB0990100040101003"),
#'                      c("TB0990100050101001", "TB0990100050101002", "TB0990100050101003"
#'                      ))
#' 
#' ## Select two aliquots per patient
#' aliquots_selected <- select_many_aliquots(samples_list, 
#'                                           aliquots = 2)
#' 
#' aliquots_selected
select_many_aliquots <- function(x, aliquots) {
  
  if (aliquots <= 0){
    stop("Number of aliquots must be specified and greater than 0")
  }
  
  aliquot_pos <- seq_len(aliquots)
  
  nms <- paste0("aliquots", aliquot_pos)
  
  list_aliquots <- vector(mode = "list",
                          length = aliquots)
  
  list_aliquots <- lapply(seq_along(aliquot_pos), function(i){
    
    aliquot_label_i <- select_one_aliquot(x, aliquot_number = i)
    aliquot_label_i
    
    
    
  }
  )
  names(list_aliquots) <- nms
  
  list_aliquots
}
