# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand # nolint: line_length_linter.

#' Select and Shuffle Rows Based on a Numeric Threshold
#'
#' This function takes a data.table, a numeric variable name, and a threshold. 
#' It separates the rows into those above and below the threshold. Rows above 
#' the threshold are shuffled. The function then combines these shuffled rows 
#' with the unshuffled rows below the threshold, maintaining the original order 
#' where possible.
#'
#' @param dt A data.table object.
#' @param numeric_var The name of the numeric variable to evaluate against the threshold.
#'           This should be provided as a character string.
#' @param threshold The numeric threshold to separate the rows.
#'           Default is 5.
#' @param seed An optional seed for reproducibility.
#' @return A data.table with rows above the threshold shuffled and 
#' @export
#' @examples
#' #select_and_shuffle_dt()
select_and_shuffle_dt <- function(dt, numeric_var, threshold = 5, seed = 123) {
    # Ensure dt is a data.table
    setDT(dt)
    
    # Add row index to maintain original order where needed

    # Split data based on threshold
    dt_above <- dt[get(numeric_var) >= threshold, ]
    dt_below <- dt[get(numeric_var) < threshold, ]
    
    # Shuffle the above threshold data table
    if (nrow(dt_above) > 0) {
        set.seed(seed) # For reproducibility, optional
        dt_above <- dt_above[sample(.N), ]
    }
    
    # Combine the shuffled above with the below threshold, maintaining group order
    dt_result <- rbindlist(list(dt_above, dt_below), use.names = TRUE)
    
    
    return(dt_result)
}

