# WARNING - Generated by {fusen} from dev/sample_selections.Rmd: do not edit by hand

#' Title Select One aliquot 
#' 
#' Description This function selects a specific aliquot label from a list of objects/ A list column 
#' @param x The input is a list column or a list of vectors 
#' @param aliquot_number The number indicating the position of the desired aliquot label. Defaults to 1.
#' @return A list of selected aliquot labels.
#' @return A vector
#' 
#' @export
#' @examples
#' library(data.table)
#' library(dplyr)
#' data("tb_data", package = "findBiobankR")
#' data("tb_specimen_df", package = "findBiobankR")
#'
#' # required clinical cols
#' clinical_cols <- c("tb_group", "hiv_status", "sex", "country") 
#'
#' clin_specs  <- convert_os_df_to_wide(clinical_df = tb_data,
#'                                      specimen_df = tb_specimen_df, 
#'                                      join_by_col = "ppid",
#'                                      specimen_col ="specimen_type" ,
#'                                      clinical_vars = clinical_cols ,
#'                                       specimen_label_col = "specimen_label",
#'                                      os_aliquot_names = c("Serum", "Plasma")
#' )
#'
#' ##
#' clin_specs[, select_one_aliquot(NP_labels_serum)]
#'
#' # or data table way
#' clin_specs[, serum_aliquot_dt := select_one_aliquot(NP_labels_serum)]
#' # or tidyverse way
#' clin_specs %>%
#'   mutate(serum_aliquot_dp := select_one_aliquot(NP_labels_serum))
#'
#' knitr::kable(clin_specs[1:10, ])
#'
#' samples_list <- list(c("TB0990100010101001", "TB0990100010101002", "TB0990100010101003"),
#'                      c("TB0990100020101001", "TB0990100020101002", "TB0990100020101003"), 
#'                      c("TB0990100030101001", "TB0990100030101002", "TB0990100030101003"),
#'                      c("TB0990100040101001", "TB0990100040101002", "TB0990100040101003"),
#'                      c("TB0990100050101001", "TB0990100050101002", "TB0990100050101003"
#'                      ))
#' select_one_aliquot(samples_list, aliquot_number = 2)


select_one_aliquot <- function(x, aliquot_number = 1){
  
  # Check if x is a list
  if (!is.list(x)) {
    stop("Parameter 'x' must be a list.")
  }
  # Check if aliquot_number is numeric
  if (isFALSE(aliquot_number %%1==0 | aliquot_number > 0)) {
    stop("Parameter 'aliquot_number' must be a non negative integer.")
  }
  
  #a list to store the selected aliquot labels
  list_aliquots <- lapply(seq_along(x),function(z){
    
    zx = x[[z]]
    
    if(is.null(zx) ){
      
      ans = NA
      
    }else if(aliquot_number > length(zx)){
      
      warning("Subscript out of bounds returning NA")
      
      ans = NA
      
    }else{
      
      ans = zx[[aliquot_number]] %>% unlist()
    }
    
    ans
  })
  
  unlist(list_aliquots)
}
