# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Convert Timestamp to Date
#'
#' This function provides a generic method and methods for numeric and data frame objects to convert
#' timestamps to date objects. It is especially useful for dealing with timestamps stored as numeric values.
#'
#' @param timestamp Numeric timestamp or a data frame with timestamp columns.
#' @param date_cols  Names of the timestamp columns to convert.
#' @return A datetime object when a numeric timestamp is provided, or a modified data frame when a
#' data frame with timestamp columns is provided.
#'
#' @export
#' 
#' @examples
#'
#' timestamp <- 1637892323000
#' datetime <- timestamp_to_date(timestamp)
#' datetime
#' # Example 2: Convert timestamp columns in a data frame
#' df <- data.frame(id = c(1, 2, 3),
#'                  event_date = c(1637892323000, 1637892423000, 1637892523000))
#'
#'
#' timestamp_to_date(df)
#'
#' df
timestamp_to_date <- function(timestamp, date_cols = NULL){
  
  UseMethod("timestamp_to_date")
  
}

#' Convert Numeric Timestamp to Date
#'
#' This method converts a numeric timestamp to a datetime object.
#'
#' @param timestamp Numeric timestamp.
#' @param date_cols Names of the timestamp columns to convert if the object timestamp is a data.frame. This is not needed for this method
#'
#' @return doesn't return anything because the data frame is converted to data.table and function applied in place.
#'
#' @export
timestamp_to_date.numeric <- function(timestamp, date_cols = NULL){
  
  timestamp <- as.numeric(timestamp)
  timestamp <- timestamp/1000
  timestamp <- lubridate::as_datetime(timestamp)
  return(timestamp)
}

#' Convert Timestamp Columns in a Data Frame to Date
#'
#' This method converts timestamp columns in a data frame to date columns.
#'
#' @param timestamp Data frame with timestamp columns.
#' @param date_cols Names of the timestamp columns to convert.
#'
#' @return A modified data frame with converted timestamp columns.
#'
#' @export
timestamp_to_date.data.frame <- function(timestamp, date_cols = NULL){
  
  
  if(is.null(date_cols)){
    
    nms <- names(timestamp)
    
    date_cols <- nms[grepl("date", nms, ignore.case = TRUE)]
    
  }
  
  data.table::setDT(timestamp)
  
  leng <- length(date_cols)
  
  if(leng != 0){
    
    timestamp[, (date_cols) := lapply(.SD, timestamp_to_date.numeric), .SDcols = date_cols]
  }
  
  
  
  
  
  
  
  
}

