# WARNING - Generated by {fusen} from dev/OpenSpecimenAPI.Rmd: do not edit by hand

#' Convert Timestamp to Date
#'
#' This function converts numeric timestamps (in milliseconds) to date-time objects. 
#' If the input contains special characters or is not numeric, it skips the conversion.
#'
#' @param timestamp A vector of timestamps which can be either numeric or character.
#' @param date_cols (Optional) Columns to be treated as date columns. Currently not used.
#' @return A vector with converted date-time objects or the original input if conversion is skipped.
#' @importFrom lubridate as_datetime
#' @export
#' @examples
#'
#' timestamps <- c("1625068800000", "1625068801000", "1625068802000")
#' converted_timestamps <- timestamp_to_date(timestamps)
#' converted_timestamps
#'
#' timestamps_numeric <- c(1625068800000, 1625068801000, 1625068802000)
#' converted_timestamps_numeric <- timestamp_to_date(timestamps_numeric)
#' converted_timestamps_numeric
#' timestamps_with_specials <- c("1625068800000", "2021-07-01 00:00:00", "1625068800/1000")
#' timestamps_with_specials <- c("1625068800000", "2021-07-01 00:00:00", "1625068800/1000")
#' timestamps_with_specials
#' # Example 2: Convert timestamp columns in a data frame
#' df <- data.frame(id = c(1, 2, 3),
#'                  event_date = c(1637892323000, 1637892423000, 1637892523000))
#'
#'
#' timestamp_to_date(df)
#'
#' df
timestamp_to_date <- function(timestamp, date_cols = NULL) {
  # Helper function to detect special characters
  has_special_characters <- function(input) {
    grepl("[-/:]", input)
  }
  
  # Helper function to check if the whole vector is all digits
  is_all_digits <- function(input) {
    all(grepl("^\\d+$", input))
  }
  
  # Check if input is a character vector and all elements are digits
  if (is.character(timestamp) && is_all_digits(timestamp)) {
    timestamp <- as.numeric(timestamp)
  }
  
  # Check if input is numeric or has special characters
  if (!is.numeric(timestamp) || any(sapply(timestamp, has_special_characters))) {
    warning("Input timestamp is not numeric or contains special characters. Skipping conversion.")
    return(timestamp)
  }
  
  # Perform the conversion
  timestamp <- as.numeric(timestamp)
  timestamp <- timestamp / 1000
  timestamp <- lubridate::as_datetime(timestamp)
  return(timestamp)
}


#' Convert Timestamp Columns in a Data Frame to Date
#'
#' This method converts timestamp columns in a data frame to date columns.
#'
#' @param timestamp Data frame with timestamp columns.
#' @param date_cols Names of the timestamp columns to convert.
#'
#' @return A modified data frame with converted timestamp columns.
#'
#' @export
timestamp_to_date.data.frame <- function(timestamp, date_cols = NULL){
  
  
  if(is.null(date_cols)){
    
    nms <- names(timestamp)
    
    date_cols <- nms[grepl("date", nms, ignore.case = TRUE)]
    
  }
  
  data.table::setDT(timestamp)
  
  leng <- length(date_cols)
  
  if(leng != 0){
    
    timestamp[, (date_cols) := lapply(.SD, timestamp_to_date), .SDcols = date_cols]
  }
  
  
  
  
  
  
  
  
}

